name: 友達紹介ポイント
code: PointsOnReferral
version: 0.1.0
service:
  - PointsOnReferralServiceProvider
orm.path:
  - /Resource/doctrine
event:
  PointsOnReferralEvent
const:
  referral_code_query_key: referral_code
  session_key: por_referral_code
